import {StyleSheet} from 'react-native';
import {moderateScale} from 'react-native-size-matters';
import Colors from '../../Constants/Colors';
import Fonts from '../../Constants/Fonts';
import {responsiveScreenWidth} from 'react-native-responsive-dimensions';
export default StyleSheet.create({
 container: {
  flex: 1,
  backgroundColor: Colors.white,
 },
 searchView: {
  width: '95%',
  justifyContent: 'space-evenly',
  alignItems: 'center',
  flexDirection: 'row',
  marginTop: '8%',
  alignSelf: 'center',
 },
 innerSeacrh: {
  width: '85%',
  justifyContent: 'space-evenly',
  backgroundColor: Colors.white,
  borderColor: Colors.pink,
  borderRadius: 14,
  borderWidth: 1,
  height: moderateScale(30),
 },
 searchText: {
  color: Colors.black,
  fontSize: 13,
  marginLeft: '4%',
  fontFamily: Fonts.montserratRegular,
 },
 earIcon: {
  width: moderateScale(22),
  height: moderateScale(22),
 },
 listContainer: {
  width: moderateScale(350),
  padding: moderateScale(7),
  backgroundColor: Colors.listColor,
  elevation: 2,
  shadowColor: '#000',
  shadowOffset: {width: 0, height: 1},
  shadowOpacity: 0.2,
  shadowRadius: 2,
  elevation: 2,
  alignSelf: 'center',
  margin: 12,
  borderRadius: 4,
 },
 itemImage: {
  height: moderateScale(140),
  width: '100%',
 },
 liveView: {
  width: moderateScale(60),
  padding: 2,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: Colors.red,
  alignSelf: 'flex-end',
  borderRadius: 3,
  marginTop: '1%',
 },
 djlistContainer: {
  width: moderateScale(150),
  padding: moderateScale(7),
  backgroundColor: Colors.listColor,
  elevation: 2,
  shadowColor: '#000',
  shadowOffset: {width: 0, height: 1},
  shadowOpacity: 0.2,
  shadowRadius: 2,
  justifyContent: 'center',
  alignSelf: 'center',
  margin: 17,
  alignItems: 'center',
  borderRadius: 6,
 },
 djView: {
  height: moderateScale(95),
  width: moderateScale(95),
  borderRadius: moderateScale(50),
  marginTop: '14%',
  backgroundColor: Colors.white,
  elevation: 2,
  shadowColor: '#000',
  shadowOffset: {width: 0, height: 1},
  shadowOpacity: 0.2,
  shadowRadius: 2,
 },
 djitemImage: {
  height: moderateScale(90),
  width: moderateScale(90),
  borderRadius: moderateScale(50),
 },
 djText: {
  fontSize: 15,
  color: Colors.black,
  fontFamily: Fonts.ralewayRegular,
 },
 djliveView: {
  width: moderateScale(60),
  padding: 2,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: Colors.red,
  alignSelf: 'flex-end',
  borderRadius: 3,
  position: 'absolute',
  top: 2,
  right: 2,
 },
 liveText: {
  color: Colors.white,
  fontSize: 12,
  fontFamily: Fonts.ralewayRegular,
 },
 listHeading: {
  fontSize: 17,
  color: Colors.black,
  marginLeft: '6%',
  marginTop: '4%',
  fontFamily: Fonts.montserratRegular,
 },
 djBtn: {
  width: '95%',
  padding: 3,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: Colors.btnColor,
  borderRadius: 4,
 },
 btnText: {
  color: Colors.white,
  fontSize: 12,
  fontFamily: Fonts.montserratMedium,
 },
 presenterEventView: {
  width: '100%',
  flexDirection: 'row',
  justifyContent: 'space-evenly',
  alignItems: 'center',
  marginTop: '5%',
  alignSelf: 'center',
 },
 presenterEventIcon: {
  width: responsiveScreenWidth(28),
  padding: 5,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: Colors.pink,
  borderRadius: 5,
 },
 topIcon: {
  width: moderateScale(65),
  height: moderateScale(65),
 },
 topText: {
  color: Colors.white,
  fontSize: 16,
  fontFamily: Fonts.montserratRegular,
 },
 welcomeText: {
  fontFamily: Fonts.montserratMedium,
  fontSize: 24,
  color: Colors.black,
  marginLeft: '5%',
  marginTop: '5%',
 },
 addEventIcon: {
  width: moderateScale(120),
  padding: 7,
  justifyContent: 'space-evenly',
  alignItems: 'center',
  alignSelf: 'flex-end',
  flexDirection: 'row',
  marginTop: '4%',
 },
 addIcon: {
  width: moderateScale(18),
  height: moderateScale(15),
 },
 addText: {
  color: Colors.black,
  fontFamily: Fonts.ralewayBold,
  fontSize: 15,
  marginRight: '9%',
 },
});
