import {StyleSheet} from 'react-native';
import {moderateScale} from 'react-native-size-matters';
import Colors from '../../Constants/Colors';
import Fonts from '../../Constants/Fonts';
export default StyleSheet.create({
 container: {
  flex: 1,
  backgroundColor: Colors.white,
 },
 heading: {
  fontFamily: Fonts.montserratMedium,
  fontSize: 17,
  color: Colors.black,
  marginLeft: '6%',
  marginTop: '4%',
 },
 listView: {
  width: '95%',
  padding: 12,
  justifyContent: 'center',
  alignSelf: 'center',
  backgroundColor: Colors.listColor,
  marginTop: '4%',
  flexDirection: 'row',
  alignItems: 'center',

  shadowOffset: {width: 0, height: 1},
  shadowOpacity: 0.2,
  shadowRadius: 2,
  elevation: 2,
  shadowColor: '#000',
 },
 innerView: {
  flexDirection: 'row',
  justifyContent: 'space-evenly',
  width: moderateScale(200),
  alignItems: 'center',
 },
 imageView: {
  width: moderateScale(70),
  height: moderateScale(70),
  borderRadius: 36,
  backgroundColor: Colors.white,
  elevation: 2,
  justifyContent: 'center',
  alignItems: 'center',
  shadowColor: '#000',
  shadowOffset: {width: 0, height: 1},
  shadowOpacity: 0.2,
  shadowRadius: 2,
  marginLeft: '-7%',
 },
 imageStyle: {
  width: moderateScale(40),
  height: moderateScale(40),
  borderRadius: 17,
 },
 itemContainer: {
  width: '50%',
  justifyContent: 'center',
  marginTop: '5%',
 },
 userText: {
  fontFamily: Fonts.montserratRegular,
  fontSize: 16,
  color: Colors.black,
 },
 descriptionText: {
  fontFamily: Fonts.montserratRegular,
  fontSize: 13,
  color: Colors.black,
  marginTop: '2%',
 },
 iconView: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  width: moderateScale(80),
  alignSelf: 'center',
  marginTop: '12%',
  right: 12,
 },
 crossIcon: {
  width: moderateScale(20),
  height: moderateScale(20),
 },
 videoView: {
  width: moderateScale(120),
  height: moderateScale(80),
  backgroundColor: Colors.black,
  marginLeft: '5%',
  justifyContent: 'center',
  alignItems: 'center',
 },
 videoBtn: {
  width: moderateScale(45),
  height: moderateScale(45),
  backgroundColor: Colors.white,
  justifyContent: 'center',
  alignItems: 'center',
  borderRadius: 25,
 },
 playIcon: {
  width: moderateScale(15),
  height: moderateScale(15),
 },
 centeredView: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  marginTop: 22,
 },
 modalView: {
  // margin: 3,
  width: '90%',
  backgroundColor: Colors.white,
  borderRadius: 7,
  padding: 5,
  alignItems: 'center',
  shadowColor: '#000',
  shadowOffset: {
   width: 0,
   height: 2,
  },
  shadowOpacity: 0.25,
  shadowRadius: 4,
  elevation: 5,
 },
 closeBtn: {
  width: moderateScale(40),
  height: moderateScale(40),
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: Colors.white,
  borderRadius: 25,
  elevation: 2,
  justifyContent: 'center',
  alignItems: 'center',
  shadowColor: '#000',
  shadowOffset: {width: 0, height: 1},
  shadowOpacity: 0.2,
  shadowRadius: 2,
  alignSelf: 'flex-end',
  position: 'absolute',
  top: moderateScale(-40),
  right: -15,
  // bottom:22,
  // left:12
 },
 logOutBtn: {
  width: '95%',
  padding: 13,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: Colors.darkGreen,
  alignSelf: 'center',
  borderRadius: 7,
  // position:'absolute',
  bottom: 8,

  elevation: 3,
  shadowColor: '#000',
  shadowOffset: {width: 0, height: 1},
  shadowOpacity: 0.2,
  shadowRadius: 2,
 },
 btnText: {
  color: Colors.white,
  fontSize: 15,
 },
});
